name: CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Publish to Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: pnpm chromatic
